name: Bug Report
description: You're experiencing an issue with WeSQL-Scale that is different than the documented behavior.
title: "[Bug Report] "
labels: ["Type: Bug", "Needs Triage"]
body:
  - type: textarea
    id: overview-of-the-issue
    attributes:
      label: Overview of the Issue
      description: A paragraph or two about the issue you're experiencing.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction Steps
      description: |
        A paragraph or two about the issue you're experiencing.
        Example:
        1. Create a table
            ```sql
            create database test1;
            use test1;
            create table user(user_id bigint, name varchar(128), primary key(user_id));
            ```
        2. Run `select * from user where user_id = 1;`
        3. View error
    validations:
      required: true

  - type: textarea
    id: binary-version
    attributes:
      label: Binary Version
      description: |
        Tell us which version of WeSQL-Scale you're using.
        Example:
        ```sh
        vtgate --version
        Version: 16.0.0 (Git revision 245cf04e6720d00beecfad0c4d7a16d3bac47bae branch 'main') built on Wed Aug 30 20:11:23 CST 2023 by earayu@yuguanghuidebijibendiannao.local using go1.20.2 darwin/arm64
        ```
      render: sh
    validations:
      required: true

  - type: textarea
    id: os-and-env
    attributes:
      label: Operating System and Environment details
      description: |
        OS, Architecture, and any other information you can provide about the environment.
        Example:
        - Operating system (output of `cat /etc/os-release`)
        - Kernel version (output of `uname -sr`)
        - Architecture (output of `uname -m`)
      render: sh
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Log Fragments
      description: Include appropriate log fragments. If the log is longer than a few dozen lines, please include the URL to the gist (https://gist.github.com/) of the log instead of posting it in the issue. This will be automatically formatted into code, so no need for backticks.
      render: sh