global:
  scrape_interval: 15s

rule_files:
  - "prometheus_rules.yaml"

scrape_configs:
  - job_name: 'vitess-vtgate'
    static_configs:
      - targets: ['host.docker.internal:15001']

  - job_name: 'vitess-vttablet'
    static_configs:
      - targets: ['host.docker.internal:15100']

#  - job_name: 'mysql'
#    static_configs:
#      - targets: ['<MySQL_HOST>:<MySQL_PORT>']

    metrics_path: '/metrics'
    scheme: 'http'