name: Branch Example

on:
  push:

jobs:
  setup-mysql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create MySQL Branch
        uses: wesql/mysql-branch-action@v0.0.4
        with:
          source_host: '47.93.127.119'
          source_port: '15306'
          source_user: 'root'
          source_password: ${{ secrets.SOURCE_PASSWORD }}
          include_databases: '*'
          exclude_databases: 'information_schema,mysql,performance_schema,sys'
          wescale_image: 'apecloud/apecloud-mysql-scale:0.3.8'

      - name: Do Your Schema Migration
        run: |
          mysql -h127.0.0.1 -P15306 -e "create database if not exists foobar"
          mysql -h127.0.0.1 -P15306 -e "create table if not exists foobar.account (id int primary key, name varchar(255))"

      - name: Branch Diff
        run: |
          mysql -h127.0.0.1 -P15306 -e "Branch diff"

      - name: Branch Prepare Merge Back
        run: |
          mysql -h127.0.0.1 -P15306 -e "Branch prepare_merge_back"

      - name: Branch Merge Back
        run: |
          mysql -h127.0.0.1 -P15306 -e "Branch merge_back"

      - name: Branch Show
        run: |
          mysql -h127.0.0.1 -P15306 -e "Branch show"