name: Branch Example

on:
  push:

jobs:
  setup-mysql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create MySQL Branch
        uses: wesql/mysql-branch-creation-action@v1
        with:
          source_host: '47.93.127.119'
          source_port: '15306' # Optional
          source_user: 'root' # Optional
          include_databases: '*' # Optional
          exclude_databases: 'information_schema,mysql,performance_schema,sys' # Optional
          wescale_image: 'apecloud/apecloud-mysql-scale:0.3.8' # Optional
        secrets:
          source_password: ${{ secrets.source_password }}

      - name: Do Your Schema Migration
        run: |
          sleep 1

      - name: Branch Diff
        run: |
          mysql -h127.0.0.1 -P15306 -e "Branch diff"

      - name: Branch Prepare Merge Back
        run: |
          mysql -h127.0.0.1 -P15306 -e "Branch prepare_merge_back"

      - name: Branch Merge Back
        run: |
          mysql -h127.0.0.1 -P15306 -e "Branch merge_back"

      - name: Branch Show
        run: |
          mysql -h127.0.0.1 -P15306 -e "Branch show"